darkcolor='#1f2324';
lightcolor='#969fa2';
let doc_path;
let pic_path;
let mon_path;
let not_path;
let bok_path;
let tra_path;
let color;
const ishome=1;
const protocol = window.location.protocol === 'file:' ? '${protocol}' : window.location.protocol;
